### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by ghost** [MycroftAI/mimic3-voices#1]
**Describe the bug**

There's no repo at the [Mimic3 link](https://github.com/MycroftAI/mimic3) in the readme.

**To Reproduce**

Click on the link, see the 404 error.

**Comment by krisgesling** [comment]
Hi John, we're just getting Mimic 3 ready for its official launch so the repo is currently private. Should have that available for you very soon... :)

**Comment by hkalbasi** [comment]
Any update on this? Are things going well?

**Comment by krisgesling** [comment]
Hey, things are going well, been addressing feedback on a number of languages from the beta preview but I think we're through the bulk of that. Can hopefully give you a release date soon

**Comment by fivestones** [comment]
Looks like this is fixed now :-)
