### ISSUE TITLE
_high quality models?

### ISSUE THREAD

**Issue by pragma-turner** [MycroftAI/mimic3-voices#3]
I really love this project! It's well-documented, and super easy to use. I was wondering if there are plans to make higher-quality models available in the mimic3 docker-container, or if there's a place I can manually download high-quality models.

Thanks for all your great work!

**Comment by llamafilm** [comment]
I was wondering the same thing.  Documentation looks great, except that it doesn't explain why all the models are low quality.

**Comment by fivestones** [comment]
Or even, what qualifies something as low vs. high quality? Some of these 'low quality' voices sound really good to me.

**Comment by synesthesiam** [comment]
"Low" and "high" quality refers to the configurations from the model's [original repository](https://github.com/jaywalnut310/vits).
